### ISSUE TITLE
Manim version in !mdoc

### ISSUE THREAD

**Issue by WampyCakes** [ManimCommunity/DiscordManimator#10]
It would be nice if you could specify the manim version you want !mdoc for for users troubleshooting a problem on old versions. Something like `!mdoc 0.4.0 LaggedStart`

**Comment by Darylgolden** [comment]
This won't be possible to truly correctly do with the implementation of `mdoc` unless the server had every version of manim installed. However, it's definitely possible to do with `!msearch`.
